apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curri-docs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: curri-docs
    spec:
      containers:
      - name: curri-docs
        image: %REGISTRY%/%APP_NAME%:%VERSION%
        ports:
        - containerPort: 9000
      tolerations:
      - operator: "Exists"
      imagePullSecrets:
      - name: regsecret

