kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-users
  annotations:
    volume.beta.kubernetes.io/storage-class: "ssd"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi